// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BlockSubmission { id: number, status: number, chain: number, reward: bigint, timeMs: bigint, durationMs: bigint, height: number, difficulty: number, effortPercent: number, hash: string, solver: string, }