// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundOverview } from "./RoundOverview";

export interface BlockOverview { currentRound: RoundOverview, height: number, orphans: number, mined: number, averageEffort: number, averageDuration: number, mined24H: number, difficulty: number, confirmations: number, }