// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SickResult } from "./SickResult";

export interface CachedSickResult<T> { expire_seconds: bigint, sick_result: SickResult<T>, }