// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MinerStats { averageHashrate: Array<number>, currentHashrate: Array<number>, invalidShares: Array<number>, staleShares: Array<number>, validShares: Array<number>, }