// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PayoutOverview { nextPayout: bigint, totalPaid: bigint, totalPayouts: number, scheme: string, fee: number, minimumThreshold: bigint, }