// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PoolOverview { poolHashrate: number, networkHashrate: number, minerCount: number, workerCount: number, }