// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WorkerStatsEntry { worker: string, averageHashrate: number, currentHashrate: number, invalidShares: number, staleShares: number, time: bigint, validShares: number, }